### ISSUE TITLE
 Update README.md

### ISSUE THREAD

**Issue by miwashutaro0611** [jonathantneal/sanitize.css#238]
README.md information is out of date and needs to be updated

### 1. Deletion of the phrase "IE support"

In v13, `:where` is used, and `:where` is not IE-compatible, so the phrase "IE-compatible" should be removed.

refer: https://caniuse.com/?search=where

### 2. Update on Area Features

The information in part `Features` is out of date and needs to be updated.
Since I don't know what the overall changes are, I will try to fix the selectors of existing rules and those that have already been removed.

e.g.

`html {` → `:where(:root)`

```css
a, area, button, input, label, select, summary, textarea, [tabindex] {
  -ms-touch-action: manipulation;
  touch-action: manipulation;
}
```

↓

delete
